/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/root'
import { Route as layoutFirstLayoutImport } from './routes/layout/first-layout'
import { Route as postsPostsImport } from './routes/posts/posts'
import { Route as homeImport } from './routes/home'
import { Route as layoutSecondLayoutImport } from './routes/layout/second-layout'
import { Route as postsPostsDetailImport } from './routes/posts/posts-detail'
import { Route as postsPostsHomeImport } from './routes/posts/posts-home'
import { Route as bImport } from './routes/b'
import { Route as aImport } from './routes/a'

// Create/Update Routes

const layoutFirstLayoutRoute = layoutFirstLayoutImport.update({
  id: '/_first',
  getParentRoute: () => rootRoute,
} as any)

const postsPostsRoute = postsPostsImport.update({
  path: '/posts',
  getParentRoute: () => rootRoute,
} as any)

const homeRoute = homeImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const layoutSecondLayoutRoute = layoutSecondLayoutImport.update({
  id: '/_second',
  getParentRoute: () => layoutFirstLayoutRoute,
} as any)

const postsPostsDetailRoute = postsPostsDetailImport.update({
  path: '/$postId',
  getParentRoute: () => postsPostsRoute,
} as any)

const postsPostsHomeRoute = postsPostsHomeImport.update({
  path: '/',
  getParentRoute: () => postsPostsRoute,
} as any)

const bRoute = bImport.update({
  path: '/layout-b',
  getParentRoute: () => layoutSecondLayoutRoute,
} as any)

const aRoute = aImport.update({
  path: '/layout-a',
  getParentRoute: () => layoutSecondLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    'home.tsx': {
      id: 'home.tsx'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeImport
      parentRoute: typeof rootRoute
    }
    'posts/posts.tsx': {
      id: 'posts/posts.tsx'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof postsPostsImport
      parentRoute: typeof rootRoute
    }
    'posts/posts-home.tsx': {
      id: 'posts/posts-home.tsx'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof postsPostsHomeImport
      parentRoute: typeof postsPostsImport
    }
    'posts/posts-detail.tsx': {
      id: 'posts/posts-detail.tsx'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof postsPostsDetailImport
      parentRoute: typeof postsPostsImport
    }
    'layout/first-layout.tsx': {
      id: 'layout/first-layout.tsx'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof layoutFirstLayoutImport
      parentRoute: typeof rootRoute
    }
    'layout/second-layout.tsx': {
      id: 'layout/second-layout.tsx'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof layoutSecondLayoutImport
      parentRoute: typeof layoutFirstLayoutImport
    }
    'a.tsx': {
      id: 'a.tsx'
      path: '/layout-a'
      fullPath: '/layout-a'
      preLoaderRoute: typeof aImport
      parentRoute: typeof layoutSecondLayoutImport
    }
    'b.tsx': {
      id: 'b.tsx'
      path: '/layout-b'
      fullPath: '/layout-b'
      preLoaderRoute: typeof bImport
      parentRoute: typeof layoutSecondLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  homeRoute,
  postsPostsRoute: postsPostsRoute.addChildren({
    postsPostsHomeRoute,
    postsPostsDetailRoute,
  }),
  layoutFirstLayoutRoute: layoutFirstLayoutRoute.addChildren({
    layoutSecondLayoutRoute: layoutSecondLayoutRoute.addChildren({
      aRoute,
      bRoute,
    }),
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "root.tsx",
      "children": [
        "home.tsx",
        "posts/posts.tsx",
        "layout/first-layout.tsx"
      ]
    },
    "home.tsx": {
      "filePath": "home.tsx"
    },
    "posts/posts.tsx": {
      "filePath": "posts/posts.tsx",
      "children": [
        "posts/posts-home.tsx",
        "posts/posts-detail.tsx"
      ]
    },
    "posts/posts-home.tsx": {
      "filePath": "posts/posts-home.tsx",
      "parent": "posts/posts.tsx"
    },
    "posts/posts-detail.tsx": {
      "filePath": "posts/posts-detail.tsx",
      "parent": "posts/posts.tsx"
    },
    "layout/first-layout.tsx": {
      "filePath": "layout/first-layout.tsx",
      "children": [
        "layout/second-layout.tsx"
      ]
    },
    "layout/second-layout.tsx": {
      "filePath": "layout/second-layout.tsx",
      "parent": "layout/first-layout.tsx",
      "children": [
        "a.tsx",
        "b.tsx"
      ]
    },
    "a.tsx": {
      "filePath": "a.tsx",
      "parent": "layout/second-layout.tsx"
    },
    "b.tsx": {
      "filePath": "b.tsx",
      "parent": "layout/second-layout.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
